set(_AMENT_PACKAGE_NAME "libstatistics_collector")
set(libstatistics_collector_VERSION "1.3.1")
set(libstatistics_collector_MAINTAINER "ROS Tooling Working Group <ros-tooling@googlegroups.com>")
set(libstatistics_collector_BUILD_DEPENDS "rosidl_default_generators" "std_msgs" "builtin_interfaces" "rcl" "rcpputils" "statistics_msgs")
set(libstatistics_collector_BUILDTOOL_DEPENDS "ament_cmake" "ament_cmake_ros")
set(libstatistics_collector_BUILD_EXPORT_DEPENDS "builtin_interfaces" "rcl" "rcpputils" "statistics_msgs")
set(libstatistics_collector_BUILDTOOL_EXPORT_DEPENDS )
set(libstatistics_collector_EXEC_DEPENDS "rosidl_default_runtime" "std_msgs" "builtin_interfaces" "rcl" "rcpputils" "statistics_msgs")
set(libstatistics_collector_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common" "performance_test_fixture")
set(libstatistics_collector_GROUP_DEPENDS )
set(libstatistics_collector_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(libstatistics_collector_DEPRECATED "")
set(libstatistics_collector_EXPORT_TAGS)
list(APPEND libstatistics_collector_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
