set(_AMENT_PACKAGE_NAME "dynmsg")
set(dynmsg_VERSION "1.0.0")
set(dynmsg_MAINTAINER "Geoffrey Biggs <geoff@openrobotics.org>")
set(dynmsg_BUILD_DEPENDS "rcutils" "rosidl_runtime_c" "rosidl_runtime_cpp" "rosidl_typesupport_introspection_c" "rosidl_typesupport_introspection_cpp" "yaml_cpp_vendor")
set(dynmsg_BUILDTOOL_DEPENDS "ament_cmake")
set(dynmsg_BUILD_EXPORT_DEPENDS "rcutils" "rosidl_runtime_c" "rosidl_runtime_cpp" "rosidl_typesupport_introspection_c" "rosidl_typesupport_introspection_cpp" "yaml_cpp_vendor")
set(dynmsg_BUILDTOOL_EXPORT_DEPENDS )
set(dynmsg_EXEC_DEPENDS "rcutils" "rosidl_runtime_c" "rosidl_runtime_cpp" "rosidl_typesupport_introspection_c" "rosidl_typesupport_introspection_cpp" "yaml_cpp_vendor")
set(dynmsg_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common" "std_msgs")
set(dynmsg_GROUP_DEPENDS )
set(dynmsg_MEMBER_OF_GROUPS )
set(dynmsg_DEPRECATED "")
set(dynmsg_EXPORT_TAGS)
list(APPEND dynmsg_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
