set(_AMENT_PACKAGE_NAME "rcl_yaml_param_parser")
set(rcl_yaml_param_parser_VERSION "5.3.4")
set(rcl_yaml_param_parser_MAINTAINER "Ivan Paunovic <ivanpauno@ekumenlabs.com>, William Woodall <william@openrobotics.org>")
set(rcl_yaml_param_parser_BUILD_DEPENDS "rcutils" "libyaml_vendor" "yaml" "rmw")
set(rcl_yaml_param_parser_BUILDTOOL_DEPENDS "ament_cmake_ros")
set(rcl_yaml_param_parser_BUILD_EXPORT_DEPENDS "libyaml_vendor" "yaml" "rmw")
set(rcl_yaml_param_parser_BUILDTOOL_EXPORT_DEPENDS )
set(rcl_yaml_param_parser_EXEC_DEPENDS "libyaml_vendor" "yaml" "rmw")
set(rcl_yaml_param_parser_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_common" "ament_lint_auto" "mimick_vendor" "osrf_testing_tools_cpp" "performance_test_fixture" "rcpputils")
set(rcl_yaml_param_parser_GROUP_DEPENDS )
set(rcl_yaml_param_parser_MEMBER_OF_GROUPS )
set(rcl_yaml_param_parser_DEPRECATED "")
set(rcl_yaml_param_parser_EXPORT_TAGS)
list(APPEND rcl_yaml_param_parser_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
