set(_AMENT_PACKAGE_NAME "wasm_cpp")
set(wasm_cpp_VERSION "0.0.0")
set(wasm_cpp_MAINTAINER "Isabel Paredes <isabel.paredes@quantstack.net>")
set(wasm_cpp_BUILD_DEPENDS "rcutils")
set(wasm_cpp_BUILDTOOL_DEPENDS "ament_cmake")
set(wasm_cpp_BUILD_EXPORT_DEPENDS "rcutils")
set(wasm_cpp_BUILDTOOL_EXPORT_DEPENDS )
set(wasm_cpp_EXEC_DEPENDS "rcutils")
set(wasm_cpp_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(wasm_cpp_GROUP_DEPENDS )
set(wasm_cpp_MEMBER_OF_GROUPS "rmw_implementation_packages")
set(wasm_cpp_DEPRECATED "")
set(wasm_cpp_EXPORT_TAGS)
list(APPEND wasm_cpp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
