set(_AMENT_PACKAGE_NAME "rmw_wasm_cpp")
set(rmw_wasm_cpp_VERSION "0.0.1")
set(rmw_wasm_cpp_MAINTAINER "Isabel Paredes <isabel.paredes@quantstack.net>")
set(rmw_wasm_cpp_BUILD_DEPENDS "rcutils" "rcpputils" "rmw" "wasm_cpp" "dynmsg" "rosidl_runtime_c" "rosidl_runtime_cpp" "rosidl_typesupport_introspection_c" "rosidl_typesupport_introspection_cpp")
set(rmw_wasm_cpp_BUILDTOOL_DEPENDS "ament_cmake")
set(rmw_wasm_cpp_BUILD_EXPORT_DEPENDS "rcutils" "rcpputils" "rmw" "wasm_cpp" "dynmsg" "rosidl_runtime_c" "rosidl_runtime_cpp" "rosidl_typesupport_introspection_c" "rosidl_typesupport_introspection_cpp")
set(rmw_wasm_cpp_BUILDTOOL_EXPORT_DEPENDS )
set(rmw_wasm_cpp_EXEC_DEPENDS "rcutils" "rcpputils" "rmw" "wasm_cpp" "dynmsg" "rosidl_runtime_c" "rosidl_runtime_cpp" "rosidl_typesupport_introspection_c" "rosidl_typesupport_introspection_cpp")
set(rmw_wasm_cpp_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(rmw_wasm_cpp_GROUP_DEPENDS )
set(rmw_wasm_cpp_MEMBER_OF_GROUPS "rmw_implementation_packages")
set(rmw_wasm_cpp_DEPRECATED "")
set(rmw_wasm_cpp_EXPORT_TAGS)
list(APPEND rmw_wasm_cpp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
