set(_AMENT_PACKAGE_NAME "yaml_cpp_vendor")
set(yaml_cpp_vendor_VERSION "8.0.2")
set(yaml_cpp_vendor_MAINTAINER "Audrow Nash <audrow@openrobotics.org>")
set(yaml_cpp_vendor_BUILD_DEPENDS "yaml-cpp")
set(yaml_cpp_vendor_BUILDTOOL_DEPENDS "ament_cmake")
set(yaml_cpp_vendor_BUILD_EXPORT_DEPENDS "yaml-cpp")
set(yaml_cpp_vendor_BUILDTOOL_EXPORT_DEPENDS )
set(yaml_cpp_vendor_EXEC_DEPENDS "yaml-cpp")
set(yaml_cpp_vendor_TEST_DEPENDS )
set(yaml_cpp_vendor_GROUP_DEPENDS )
set(yaml_cpp_vendor_MEMBER_OF_GROUPS )
set(yaml_cpp_vendor_DEPRECATED "")
set(yaml_cpp_vendor_EXPORT_TAGS)
list(APPEND yaml_cpp_vendor_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
