# generated from colcon_core/shell/template/command_prefix.sh.em
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_lint/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/osrf_pycommon/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_flake8/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_pep257/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_copyright/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_index_python/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/launch/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/launch_xml/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/launch_yaml/package.sh"
