set(_AMENT_PACKAGE_NAME "rosidl_typesupport_cpp")
set(rosidl_typesupport_cpp_VERSION "2.0.1")
set(rosidl_typesupport_cpp_MAINTAINER "Chris Lalancette <clalancette@openrobotics.org>, Shane Loretz <sloretz@openrobotics.org>")
set(rosidl_typesupport_cpp_BUILD_DEPENDS "rosidl_runtime_c" "rosidl_typesupport_c" "rosidl_typesupport_introspection_cpp" "rcutils" "rcpputils")
set(rosidl_typesupport_cpp_BUILDTOOL_DEPENDS "ament_cmake_ros")
set(rosidl_typesupport_cpp_BUILD_EXPORT_DEPENDS "rosidl_typesupport_c" "rosidl_runtime_c" "rosidl_runtime_cpp" "rcutils" "rcpputils")
set(rosidl_typesupport_cpp_BUILDTOOL_EXPORT_DEPENDS "python3" "ament_cmake_core")
set(rosidl_typesupport_cpp_EXEC_DEPENDS "ament_index_python" "rosidl_cli" "rosidl_typesupport_interface" "rcutils" "rcpputils")
set(rosidl_typesupport_cpp_TEST_DEPENDS "ament_lint_auto" "ament_lint_common" "performance_test_fixture")
set(rosidl_typesupport_cpp_GROUP_DEPENDS "rosidl_typesupport_cpp_packages")
set(rosidl_typesupport_cpp_MEMBER_OF_GROUPS "rosidl_runtime_packages")
set(rosidl_typesupport_cpp_DEPRECATED "")
set(rosidl_typesupport_cpp_EXPORT_TAGS)
list(APPEND rosidl_typesupport_cpp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
