set(_AMENT_PACKAGE_NAME "rosidl_runtime_cpp")
set(rosidl_runtime_cpp_VERSION "3.1.5")
set(rosidl_runtime_cpp_MAINTAINER "Michel Hidalgo <michel@ekumenlabs.com>, Shane Loretz <sloretz@openrobotics.org>")
set(rosidl_runtime_cpp_BUILD_DEPENDS "rosidl_runtime_c")
set(rosidl_runtime_cpp_BUILDTOOL_DEPENDS "ament_cmake")
set(rosidl_runtime_cpp_BUILD_EXPORT_DEPENDS "rosidl_runtime_c")
set(rosidl_runtime_cpp_BUILDTOOL_EXPORT_DEPENDS "ament_cmake")
set(rosidl_runtime_cpp_EXEC_DEPENDS "rosidl_runtime_c")
set(rosidl_runtime_cpp_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common" "performance_test_fixture")
set(rosidl_runtime_cpp_GROUP_DEPENDS )
set(rosidl_runtime_cpp_MEMBER_OF_GROUPS "rosidl_runtime_packages")
set(rosidl_runtime_cpp_DEPRECATED "")
set(rosidl_runtime_cpp_EXPORT_TAGS)
list(APPEND rosidl_runtime_cpp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
