set(_AMENT_PACKAGE_NAME "rosidl_generator_cpp")
set(rosidl_generator_cpp_VERSION "3.1.5")
set(rosidl_generator_cpp_MAINTAINER "Michel Hidalgo <michel@ekumenlabs.com>, Shane Loretz <sloretz@openrobotics.org>")
set(rosidl_generator_cpp_BUILD_DEPENDS )
set(rosidl_generator_cpp_BUILDTOOL_DEPENDS "ament_cmake")
set(rosidl_generator_cpp_BUILD_EXPORT_DEPENDS "rosidl_generator_c" "rosidl_runtime_cpp")
set(rosidl_generator_cpp_BUILDTOOL_EXPORT_DEPENDS "ament_cmake_core" "python3" "rosidl_cmake")
set(rosidl_generator_cpp_EXEC_DEPENDS "ament_index_python" "rosidl_cli" "rosidl_parser")
set(rosidl_generator_cpp_TEST_DEPENDS "ament_cmake_gtest" "ament_lint_auto" "ament_lint_common" "rosidl_cmake" "rosidl_runtime_cpp" "rosidl_runtime_c" "test_interface_files")
set(rosidl_generator_cpp_GROUP_DEPENDS )
set(rosidl_generator_cpp_MEMBER_OF_GROUPS "rosidl_generator_packages")
set(rosidl_generator_cpp_DEPRECATED "")
set(rosidl_generator_cpp_EXPORT_TAGS)
list(APPEND rosidl_generator_cpp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
