# generated from colcon_core/shell/template/command_prefix.sh.em
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_package/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_core/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_export_definitions/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_export_include_directories/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_export_libraries/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_export_link_flags/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_include_directories/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_libraries/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_python/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_version/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_export_dependencies/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_export_interfaces/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_export_targets/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_target_dependencies/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_test/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake_gen_version_h/package.sh"
. "/home/Ros2Wasm/tst/ros2wasm-builder/install/share/ament_cmake/package.sh"
