set(_AMENT_PACKAGE_NAME "launch_testing_ament_cmake")
set(launch_testing_ament_cmake_VERSION "1.0.4")
set(launch_testing_ament_cmake_MAINTAINER "Aditya Pande <aditya.pande@openrobotics.org>, Michel Hidalgo <michel@ekumenlabs.com>")
set(launch_testing_ament_cmake_BUILD_DEPENDS )
set(launch_testing_ament_cmake_BUILDTOOL_DEPENDS "ament_cmake")
set(launch_testing_ament_cmake_BUILD_EXPORT_DEPENDS )
set(launch_testing_ament_cmake_BUILDTOOL_EXPORT_DEPENDS "ament_cmake_test" "python_cmake_module" "launch_testing")
set(launch_testing_ament_cmake_EXEC_DEPENDS )
set(launch_testing_ament_cmake_TEST_DEPENDS "ament_cmake_copyright" "launch_testing" "python_cmake_module")
set(launch_testing_ament_cmake_GROUP_DEPENDS )
set(launch_testing_ament_cmake_MEMBER_OF_GROUPS )
set(launch_testing_ament_cmake_DEPRECATED "")
set(launch_testing_ament_cmake_EXPORT_TAGS)
list(APPEND launch_testing_ament_cmake_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
